export const pageRoutes = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  DEVPP: "/++",
  READING_LIST: "/reading-list",
  NEW_POST: "/new",
  POST: "/post",
  PODCASTS: "/podcasts",
  VIDEOS: "/videos",
  TAGS: "/tags",
  SEARCH: "/search",
  NOTIFICATIONS: "/notifications",
  PROFILES: "/profile",
  LATEST: "/latest",
  TOP: "/top",
  SELF: "/self",
  SETTINGS: "/settings",
}