import "~/styles/globals.css";

import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";

import HeaderBar from "~/app/_components/Header/HeaderBar";
import SessionProviderWrapper from "../_components/SessionProviderWrapper";
import {HydrateClient} from "~/trpc/server";

export const metadata: Metadata = {
  title: "DEV Community",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/devto_ic.svg" }],
};

export default function SearchPageLayout({
   children,
 }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="font-dev">
    <body className="">
    <SessionProviderWrapper>
      <TRPCReactProvider>
        <HydrateClient>
          <HeaderBar/>
          <main className="bg-gray-100">
            {children}
          </main>
        </HydrateClient>
      </TRPCReactProvider>
    </SessionProviderWrapper>
    </body>
    </html>
  );
}
