import "~/styles/globals.css";

import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";

import SessionProviderWrapper from "../_components/SessionProviderWrapper";
import TransparentNavBar from "~/app/_components/Header/TransparentNavBar";
import NewPostContainer from "~/app/_components/Container/NewPostContainer";
import {HydrateClient} from "~/trpc/server";

export const metadata: Metadata = {
  title: "DEV Community",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/devto-logo.png" }],
};

export default function AuthLayout({
   children,
 }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="font-dev">
    <body className="bg-gray-100 h-screen">
    <SessionProviderWrapper>
      <TRPCReactProvider>
        <HydrateClient>
          <TransparentNavBar/>
          <NewPostContainer>
            {children}
          </NewPostContainer>
        </HydrateClient>
      </TRPCReactProvider>
    </SessionProviderWrapper>
    </body>
    </html>
  );
}
